### ISSUE TITLE
[Feat] Entity 매핑 및 레포지토리 등 생성

### ISSUE THREAD

**Issue by JunSang1121** [Dev-Race/DevRace-backend#8]
## Description
Entity 매핑 및 레포지토리,서비스,컨트롤러 기초 생성.

## In Progress
- [x] Entity 작성 및 매핑
- [x] Repository 작성
- [x] Service 작성
- [x] Controller 작성

**Comment by JunSang1121** [comment]
@tkguswls1106 #8 현재 이슈에 #14 이슈를 합쳐서 PR 하려고 합니다. #14 이슈에 대한 삭제 검토를 요청드립니다.

**Comment by tkguswls1106** [comment]
> @tkguswls1106 #8 현재 이슈에 #14 이슈를 합쳐서 PR 하려고 합니다. #14 이슈에 대한 삭제 검토를 요청드립니다.

검토 완료했습니다. 요청하신대로 #14 이슈를 삭제 조치하였습니다.
이제 #8 이슈에 대한 내용 수정을 합친 내용으로 수정해주세요.
